gpts/front/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from . views import HomeView
urlpatterns = [
    
    path('', HomeView.as_view(), name='home'),
    # path('',include('front.urls') ),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gpts/gforms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from . views import HomeView
app_name = 'gforms'
urlpatterns = [
    
    path('', HomeView.as_view(), name='home'),
    # path('',include('front.urls') ),
    ######################################################################################################
    path('period/', views.periodListView.as_view(), name='products_list'),
    path('period/new/', views.periodCreateView.as_view(), name='products_new'),
    path('period/detail/<int:pk>/', views.periodDetailView.as_view(), name='products_detail'),
    path('period/update/<int:pk>/', views.periodUpdateView.as_view(), name='products_update'),
    
     ######################################################################################################
    path('category/', views.categoryListView.as_view(), name='category_list'),
    path('category/new/', views.categoryCreateView.as_view(), name='category_new'),
    path('category/detail/<int:pk>/', views.categoryDetailView.as_view(), name='category_detail'),
    path('category/update/<int:pk>/', views.categoryUpdateView.as_view(), name='category_update'),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gpts/gpts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers


from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('back/' ,include('gforms.urls', namespace='gforms')),
    path('' ,include('front.urls')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gpts/front/models.py
from django.db import models
import datetime
from gforms.models import User , school

class period (models.Model):
    input_date=models.DateField(auto_now_add=True, editable=False)
    start_date = models.DateField()
    end_date = models.DateField()
    created_by = models.ForeignKey(User,null=True, related_name='created_by',on_delete=models.SET_NULL)
    modified= models.BooleanField(default=True)
    modified_by = models.ForeignKey(User,null=True, related_name='modified_by',on_delete=models.SET_NULL)
    modified_date = models.DateField()
    is_active = models.BooleanField(default=False)
    
    
    
class category(models.Model):
    input_date=models.DateField(auto_now_add=True, editable=False)
    category_name = models.CharField(max_length=30)
    created_by = models.ForeignKey(User,null=True, related_name='made_by',on_delete=models.SET_NULL)
    
    category_secrate_key= models.CharField(max_length=100)
    google_form_link = models.TextField(default="null")
    category_description= models.TextField(default='Please answer all the questions in this category')
    category_status=models.BooleanField(default=False)
    
    def __str__(self):
        return self.category_name

class champions (models.Model):
    input_date=models.DateField(auto_now_add=True, editable=False)
    year_won = models.DateField()
    category_won= models.ForeignKey(category, on_delete=models.CASCADE)
    school_won= models.ForeignKey(school, on_delete=models.CASCADE)
    

    
    
    
    

gpts/front/views.py
from django.shortcuts import render
from django.views.generic import View 
from .  models import period 
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.

class HomeView(View):
    def get(self, request, *args, **kwargs):
        
        try:
            periods = period.objects.get(is_active=True)
            return render(request, 'front/index.html', {'periods': periods})
        
        except ObjectDoesNotExist:
            
            
            return render(request, 'front/index.html' )
      
            
            
        

gpts/templates/front/base.html
<!doctype html>
{% load static %}

<html class="no-js" lang="zxx">
{% include 'front/head.html' %}
{% include 'front/header.html' %}

{% block content %}


{% endblock content %}



{% include 'front/footer.html' %}
{% include 'front/scripts.html' %}


</html>

gpts/templates/front/category_detail.html
{% extends 'userinterfacedesign/base.html' %}
{% block content %}

{% if user.is_authenticated %}
<div>
<div id="viewmail" class="tab-pane fade in animated zoomInDown shadow-reset custom-inbox-message">
  <div class="view-mail-wrap ">
    <div class="mail-title">
      <h2 class='text-center'>{{category.category_name}} Details</h2>
      <div class="view-mail-action">
        <a href="#"><i class="fa "></i> Cancel</a>
        <a class="compose-draft-bt" href="{% url 'gforms:category_update' pk=category.pk %}"><i class="fa "></i> Edit</a>
      
      </div>
    </div>

    <p> {{category.id}} <p>
    <p> Category Name : {{category.category_name}}</p>
    <p> Category Secrate Key : {{category.category_secrate_key}}</p>
    <p> Created By : {{category.created_by}}</p>
    <p> Google form Link : {{category.google_form_link}}</p>
    <p> Category Description : {{category.category_description}}</p>
    <p> Category Status : {{category.category_status}}</p>
    



      {% endif %}
</div>
</div>
</div>

      {% endblock content %}

gpts/templates/front/category_form.html
{% extends 'userinterfacedesign/base.html' %}
{% load static %}
{% block content %}
{% load bootstrap4 %}

<div class="login-form-area mg-t-30 mg-b-15">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-3"></div>

      <div class="col-lg-6">
        <div class="login-bg">

          <div class="row">
            <div class="col-lg-12">
              <div class="login-title">
                <h1 class='text-center'> New Category</h1>
              </div>
            </div>
          </div>
          <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}

            <div class="row">
              <div class="col-lg-4"></div>
              <div class="col-lg-8">
                <div class="login-button-pro">
                  <button type="submit" class="login-button login-button-lg">Add</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>

  </div>
</div>
</div>

{% endblock content %}

gpts/templates/front/category_list.html
{% extends 'userinterfacedesign/base.html' %}
{% load static %}
{% block content %}

<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="sparkline13-list shadow-reset">
                    <div class="sparkline13-hd">
                        <div class="main-sparkline13-hd">
                            <h1>Projects <span class="table-project-n">Data</span> Table</h1>
                            <div class="sparkline13-outline-icon">
                                <span class="sparkline13-collapse-link"><i class="fa fa-chevron-up"></i></span>
                                <span><i class="fa fa-wrench"></i></span>
                                <span class="sparkline13-collapse-close"><i class="fa fa-times"></i></span>
                            </div>
                        </div>
                    </div>
                    <div class="sparkline13-graph">
                        <div class="datatable-dashv1-list custom-datatable-overright">
                            <div id="toolbar">
                                <select class="form-control">
                                    <option value="">Export Basic</option>
                                    <option value="all">Export All</option>
                                    <option value="selected">Export Selected</option>
                                </select>
                            </div>
                            <table id="table" data-toggle="table" data-pagination="true" data-search="true"
                                data-show-columns="true" data-show-pagination-switch="true" data-show-refresh="true"
                                data-key-events="true" data-show-toggle="true" data-resizable="true" data-cookie="true"
                                data-cookie-id-table="saveId" data-show-export="true" data-click-to-select="true"
                                data-toolbar="#toolbar">
                                <thead>
                                <tr>
                                        <th data-field="state" data-checkbox="true"></th>
                                        <th data-field="id">ID</th>
                                        <th data-field="Category Name" data-editable="false">Category Name</th>
                                        <th data-field="input Date" data-editable="false">input Date</th>
               
                                        <th data-field="Created By" data-editable="false"> Created By</th>
                                       
                                        <th data-field="category_secrate_key" data-editable="false">secrate key</th>
                                        <th data-field="category_status" data-editable="false">Status</th>
                                      
  
                                        <th data-field="" data-editable="false">Action</th>
                                    </tr>
                                                                </thead>

                               
                                    {% for product in category %}
                                     
                                        <tr>
                                                                        <td></td>
                                        <td>{{product.id}}</td>
                                        <td>{{product.category_name}}</td>
                                        <td>{{product.input_date}}</td>
                                       
                                        <td>{{product.created_by}}</td>
                                        <td>{{product.category_secrate_key}}</td>
                                        <td>{{product.category_status}}</td>
                                       
                                         <td>
                                           <a href="{% url 'gforms:category_detail' pk=product.pk %}"> <button class="btn btn-info">View</button></a>
                                        </td> 
                                      </tr>
                                       {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Static Table End -->
</div>
</div>

        
   

</div>







{% endblock content %}

gpts/templates/front/category_update_form.html
{% extends 'userinterfacedesign/base.html' %}
{% load bootstrap4 %}

{% block content %}

<div class="login-form-area mg-t-30 mg-b-15">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-3"></div>

      <div id="adminpro-order-form" class="adminpro-form">
        <div class="col-lg-6">
          <div class="login-bg">
            <div class="row">
              <div class="col-lg-12">
                <div class="logo">
                  <a href="#"><img src="img/logo/logo.png" alt="" />
                  </a>
                </div>
              </div>
            </div>
            <form method="post">
              {% csrf_token %}

                {% for element in form %}
                <div class="row  table">
                <div class="col-lg-4 mx-auto">
                  <div class="login-input-head">
                    {{element.label}}
                  </div>
                </div>
                <div class="col-lg-8">
                  <div class="login-input-area">
                    {{element}}
                  </div>
                </div>
                </div>
                {% endfor %}

                <input type="submit" class="btn btn-info" value="Update Product">

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

gpts/templates/front/footer.html
{% load static %}
   
   
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-4">
            <h2 class="footer-heading mb-3">About Us</h2>
                <p class="mb-5">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>

                <h2 class="footer-heading mb-4">Newsletter</h2>
                <form action="#" class="d-flex" class="subscribe">
                  <input type="text" class="form-control mr-3" placeholder="Email">
                  <input type="submit" value="Send" class="btn btn-primary">
                </form>
          </div>
          <div class="col-lg-8 ml-auto">
            <div class="row">
              <div class="col-lg-4 ml-auto">
                <h2 class="footer-heading mb-4">Navigation</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
              <div class="col-lg-4">
                <h2 class="footer-heading mb-4">Navigation</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
                
              </div>

              
              
            </div>
          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <div class="border-top pt-5">
              <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
            </div>
          </div>

        </div>
      </div>
    </footer>

    </div>

gpts/templates/front/gallery.html
<!doctype html>
<html lang="en">

  <head>
    <title>Kiddy &mdash; Website Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=DM+Sans:300,400,700|Indie+Flower" rel="stylesheet">
    

    <link rel="stylesheet" href="fonts/icomoon/style.css">

    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="css/jquery.fancybox.min.css">
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <link rel="stylesheet" href="css/owl.theme.default.min.css">
    <link rel="stylesheet" href="fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="css/aos.css">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="css/style.css">

  </head>

  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

    
    <div class="site-wrap" id="home-section">

      <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
          <div class="site-mobile-menu-close mt-3">
            <span class="icon-close2 js-menu-toggle"></span>
          </div>
        </div>
        <div class="site-mobile-menu-body"></div>
      </div>



      <header class="site-navbar site-navbar-target" role="banner">

        <div class="container mb-3">
          <div class="d-flex align-items-center">
            <div class="site-logo mr-auto">
              <a href="index.html">Kiddy<span class="text-primary">.</span></a>
            </div>
            <div class="site-quick-contact d-none d-lg-flex ml-auto ">
              <div class="d-flex site-info align-items-center mr-5">
                <span class="block-icon mr-3"><span class="icon-map-marker text-yellow"></span></span>
                <span>34 Street Name, City Name Here, <br> United States</span>
              </div>
              <div class="d-flex site-info align-items-center">
                <span class="block-icon mr-3"><span class="icon-clock-o"></span></span>
                <span>Sunday - Friday 8:00AM - 4:00PM <br> Saturday CLOSED</span>
              </div>
              
            </div>
          </div>
        </div>


        <div class="container">
          <div class="menu-wrap d-flex align-items-center">
            <span class="d-inline-block d-lg-none"><a href="#" class="text-black site-menu-toggle js-menu-toggle py-5"><span class="icon-menu h3 text-black"></span></a></span>

              

              <nav class="site-navigation text-left mr-auto d-none d-lg-block" role="navigation">
                <ul class="site-menu main-menu js-clone-nav mr-auto ">
                  <li><a href="index.html" class="nav-link">Home</a></li>
                  <li><a href="about.html" class="nav-link">About</a></li>
                  <li><a href="packages.html" class="nav-link">Packages</a></li>
                  <li class="active"><a href="gallery.html" class="nav-link">Gallery</a></li>
                  <li><a href="pricing.html" class="nav-link">Pricing</a></li>
                  <li><a href="contact.html" class="nav-link">Contact</a></li>
                </ul>
              </nav>

              <div class="top-social ml-auto">
                <a href="#"><span class="icon-facebook text-teal"></span></a>
                <a href="#"><span class="icon-twitter text-success"></span></a>
                <a href="#"><span class="icon-linkedin text-yellow"></span></a>
              </div>
          </div>
        </div>

       

      </header>

    <div class="ftco-blocks-cover-1">
       <!-- data-stellar-background-ratio="0.5" style="background-image: url('images/hero_1.jpg')" -->
      <div class="site-section-cover overlay" data-stellar-background-ratio="0.5" style="background-image: url('images/hero_1.jpg')">
        <div class="container">
          <div class="row align-items-center ">

            <div class="col-md-5 mt-5 pt-5">
              <span class="text-cursive h5 text-red">Gallery</span>
              <h1 class="mb-3 font-weight-bold text-teal">Gallery Of Kids</h1>
              <p><a href="index.html" class="text-white">Home</a> <span class="mx-3">/</span> <strong>Gallery</strong></p>
            </div>
            
          </div>
        </div>
      </div>
    </div>


    <div class="site-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-12 text-center">
            <span class="text-cursive h5 text-red d-block">Our Gallery</span>
            <h2 class="text-black">Gallery Of The Kids</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-3 mb-4">
            <a href="images/img_1.jpg" data-fancybox="gal"><img src="images/img_1.jpg" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-3 mb-4">
            <a href="images/img_2.jpg" data-fancybox="gal"><img src="images/img_2.jpg" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-3 mb-4">
            <a href="images/img_3.jpg" data-fancybox="gal"><img src="images/img_3.jpg" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-3 mb-4">
            <a href="images/img_4.jpg" data-fancybox="gal"><img src="images/img_4.jpg" alt="Image" class="img-fluid"></a>
          </div>

          <div class="col-md-3 mb-4">
            <a href="images/img_5.jpg" data-fancybox="gal"><img src="images/img_5.jpg" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-3 mb-4">
            <a href="images/img_2.jpg" data-fancybox="gal"><img src="images/img_3.jpg" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-3 mb-4">
            <a href="images/img_2.jpg" data-fancybox="gal"><img src="images/img_2.jpg" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-3 mb-4">
            <img src="images/img_1.jpg" alt="Image" class="img-fluid">
          </div>
        </div>
      </div>
    </div>
    

    


    <div class="site-section py-5 bg-warning">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-12 d-flex">
          <h2 class="text-white m-0">Bring Fun Life To Your Kids</h2>
          <a href="#" class="btn btn-primary btn-custom-1 py-3 px-5 ml-auto">Get Started</a>
          </div>
        </div>
      </div>
    </div>
    

    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-4">
            <h2 class="footer-heading mb-3">About Us</h2>
                <p class="mb-5">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>

                <h2 class="footer-heading mb-4">Newsletter</h2>
                <form action="#" class="d-flex" class="subscribe">
                  <input type="text" class="form-control mr-3" placeholder="Email">
                  <input type="submit" value="Send" class="btn btn-primary">
                </form>
          </div>
          <div class="col-lg-8 ml-auto">
            <div class="row">
              <div class="col-lg-4 ml-auto">
                <h2 class="footer-heading mb-4">Navigation</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
              <div class="col-lg-4">
                <h2 class="footer-heading mb-4">Navigation</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
                
              </div>

              
              
            </div>
          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <div class="border-top pt-5">
              <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
            </div>
          </div>

        </div>
      </div>
    </footer>

    </div>

    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="js/jquery-migrate-3.0.0.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/jquery.sticky.js"></script>
    <script src="js/jquery.waypoints.min.js"></script>
    <script src="js/jquery.animateNumber.min.js"></script>
    <script src="js/jquery.fancybox.min.js"></script>
    <script src="js/jquery.stellar.min.js"></script>
    <script src="js/jquery.easing.1.3.js"></script>
    <script src="js/bootstrap-datepicker.min.js"></script>
    <script src="js/aos.js"></script>

    <script src="js/main.js"></script>

  </body>

</html>

gpts/templates/front/head.html
<!doctype html>

{% load static %}
<html lang="en">

  <head>
    <title>GPTS &mdash; Developed by Kantet</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=DM+Sans:300,400,700|Indie+Flower" rel="stylesheet">
    

    <link rel="stylesheet" href="{% static 'front/fonts/icomoon/style.css ' %}">

    <link rel="stylesheet" href="{% static 'front/css/bootstrap.min.css ' %}">
    <link rel="stylesheet" href="{% static 'front/css/bootstrap-datepicker.css ' %}">
    <link rel="stylesheet" href="{% static 'front/css/jquery.fancybox.min.css ' %}">
    <link rel="stylesheet" href="{% static 'front/css/owl.carousel.min.css ' %}">
    <link rel="stylesheet" href="{% static 'front/css/owl.theme.default.min.css ' %}">
    <link rel="stylesheet" href="{% static 'front/fonts/flaticon/font/flaticon.css ' %}">
    <link rel="stylesheet" href="{% static 'front/css/aos.css ' %}">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static 'front/css/style.css ' %}">

  </head>

  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

gpts/templates/front/header.html
   {% load static %}  
    
    <div class="site-wrap" id="home-section">

      <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
          <div class="site-mobile-menu-close mt-3">
            <span class="icon-close2 js-menu-toggle"></span>
          </div>
        </div>
        <div class="site-mobile-menu-body"></div>
      </div>



     
     
      <header class="site-navbar site-navbar-target" role="banner">

        <div class="container mb-3">
          <div class="d-flex align-items-center">
            <div class="site-logo mr-auto">
              <a href="index.html">Great Places to school <span class="text-primary">.</span></a>
            </div>
            <div class="site-quick-contact d-none d-lg-flex ml-auto ">
              <div class="d-flex site-info align-items-center mr-5">
                <span class="block-icon mr-3"><span class="icon-map-marker text-yellow"></span></span>
                <span>34 Street Name, City Name Here, <br> United States</span>
              </div>
              <div class="d-flex site-info align-items-center">
                <span class="block-icon mr-3"><span class="icon-clock-o"></span></span>
               {% if periods %}
                <span>Start Date - {{periods.start_date}} <br> End Date - {{periods.end_date}}</span>
               {% else %}
                <span>Start Date - Closed <br> End Date - Closed</span>
                {% endif %}
              </div>
              
            </div>
          </div>
        </div>


        <div class="container">
          <div class="menu-wrap d-flex align-items-center">
            <span class="d-inline-block d-lg-none"><a href="#" class="text-black site-menu-toggle js-menu-toggle py-5"><span class="icon-menu h3 text-black"></span></a></span>

              

              <nav class="site-navigation text-left mr-auto d-none d-lg-block" role="navigation">
                <ul class="site-menu main-menu js-clone-nav mr-auto ">
                  <li class="active"><a href="index.html" class="nav-link">Home</a></li>
                  <li><a href="about.html" class="nav-link">About</a></li>
                  <li><a href="packages.html" class="nav-link">Packages</a></li>
                  <li><a href="gallery.html" class="nav-link">Gallery</a></li>
                  <li><a href="pricing.html" class="nav-link">Pricing</a></li>
                  <li><a href="contact.html" class="nav-link">Contact</a></li>
                </ul>
              </nav>

              <div class="top-social ml-auto">
                <a href="#"><span class="icon-facebook text-teal"></span></a>
                <a href="#"><span class="icon-twitter text-success"></span></a>
                <a href="#"><span class="icon-linkedin text-yellow"></span></a>
              </div>
          </div>
        </div>

       

      </header>

gpts/templates/front/scripts.html
{% load static %}


    <script src="{% static 'front/js/jquery-3.3.1.min.js ' %}"></script>
    <script src="{% static 'front/js/jquery-migrate-3.0.0.js ' %}"></script>
    <script src="{% static 'front/js/popper.min.js ' %}"></script>
    <script src="{% static 'front/js/bootstrap.min.js ' %}"></script>
    <script src="{% static 'front/js/owl.carousel.min.js ' %}"></script>
    <script src="{% static 'front/js/jquery.sticky.js ' %}"></script>
    <script src="{% static 'front/js/jquery.waypoints.min.js ' %}"></script>
    <script src="{% static 'front/js/jquery.animateNumber.min.js ' %}"></script>
    <script src="{% static 'front/js/jquery.fancybox.min.js ' %}"></script>
    <script src="{% static 'front/js/jquery.stellar.min.js ' %}"></script>
    <script src="{% static 'front/js/jquery.easing.1.3.js ' %}"></script>
    <script src="{% static 'front/js/bootstrap-datepicker.min.js ' %}"></script>
    <script src="{% static 'front/js/aos.js ' %}"></script>

    <script src="{% static 'front/js/main.js ' %}"></script>

  </body>

</html>